# Generated by Django 4.1.5 on 2023-01-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Codes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=255)),
                ('holder_status', models.CharField(max_length=105)),
                ('link_from', models.CharField(max_length=255)),
                ('image', models.ImageField(default='./static/background.jpg', upload_to='')),
            ],
        ),
    ]
